kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-python-example
data:
  hawkular-openshift-agent: |
    collection_interval_secs: 10
    endpoints:
    - type: prometheus
      protocol: "http"
      port: 8181
      path: /
      metrics:
      - name: process_virtual_memory_bytes
        type: gauge
